base:
  random_state: 42
data:
  dataset_csv: 'data/iris.csv'
  processed_path: 'data/processed.csv'
  features_path: 'data/features.csv'
  trainset_path: 'data/train_iris.csv'
  testset_path: 'data/test_iris.csv'
  test_size: 0.3
  random_state: 42

training:
  clf_params:
    'C': .004
    'solver': 'lbfgs'
    'multi_class': 'multinomial'
    'max_iter': 150
  model_path: 'model/model.pkl'

reports:
  metrics_file: 'eval/metrics.json'
  confusion_matrix_file: 'eval/confusion_matrix.png'

